### PR TITLE
Add Missing Storage Controllers

### PR DESCRIPTION
**Pull request by jpts**
Add missing storage controller interfaces as of Virtualbox 6.1

### CODE REVIEW

**Comment by VoyTechnology** [comment]
What happens when the user tries to run it on an older version of VirtualBox? Would we have to add a minimum VirtualBox version requirement?

**Comment by jpts** [comment]
Good point. Which versions of Virtualbox do you support?

**Comment by VoyTechnology** [comment]
That is a good question I don't know the answer too. I would hazard a guess and say Virtualbox 6+. Would you have any method of validating this change with 6.0? Looking at the changelog it seems like these storage options were added pre-6.0, so I think we should be good. Also, since this package is pre 1.0, I don't think there is an assumption of compatibility guarantee.

@ringods would you agree to merging this change if we cannot validate and guarantee backwards compatibility?

**Review by VoyTechnology — APPROVED** [review]
LGTM!

**Pull request merged**
