### PR TITLE
Nat network support

### PR DESCRIPTION
**Pull request by isage**
Initial support for creating, configuring and destroying virtualbox nat networks.

### CODE REVIEW

**Comment by nevill** [comment]
Can you explain more on the difference between `NAT` and `NATNetwork`? From the [manual](https://www.virtualbox.org/manual/ch06.html), it seems `NATNetwork = NAT + Hostonly`, right?

**Comment by isage** [comment]
Main difference is that machines with NAT type NICs get the same ip, and
can't communicate, but natnetwork is a virtual network, e.g. all machines
on this network are behind virtual router, they get different ips and can
communicate with each other

**Comment by patsevanton** [comment]
@nevill Can you check PR? Thanks

**Comment by jpts** [comment]
Hi folks, I'm interested in getting this functionality merged in. Is there anything else that needs to be done for this, except for rebasing and resolving conflicts? 

@isage are you still interested in picking this up, or should I create a new PR to pickup the work in?

**Comment by VoyTechnology** [comment]
Closing in favour of #18, as stated in https://github.com/terra-farm/terraform-provider-virtualbox/pull/82#issuecomment-836218735

**Pull request closed without merging**
