### PR TITLE
Basic shared folders support

### PR DESCRIPTION
**Pull request by mlitvin**

### CODE REVIEW

**Comment by dlsniper** [comment]
Is there any interest to merge this? If so, I'd be happy to pick up the work and update the PR to the latest sources.

**Comment by mlitvin** [comment]
Personally I moved on and don't have any need for the code

**Comment by ringods** [comment]
@dlsniper yes please. If you could update the PR, please add some tests. There is a complete mock setup available to emulate the `VBoxManage` commands and responses.

**Comment by VoyTechnology** [comment]
Hi @dlsniper, I am looking at older issues and pull requests to tidy the repo up a bit. Since the original author said that it is no longer needed for them, I am closing this PR. If you would like to have this functionality added still please feel free to create a PR or an issue!

**Pull request closed without merging**
